---
server:
  port: 8989


turbine:
  aggregator:
    clusterConfig: CRUDOPERATIONS,SUMCALC,AUTHSERVICE,CATALOGUESERVICE,CUSTOMERSERVICE,ORDERSERVICE,SHIPPINGSERVICE
  appConfig: CRUDOPERATIONS,SUMCALC,AUTHSERVICE,CATALOGUESERVICE,CUSTOMERSERVICE,ORDERSERVICE,SHIPPINGSERVICE

logging:
  level: INFO